name: CI/CD Pipeline

on:
  push:
    branches:
      - samo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo service docker start

    - name: Build Docker images
      run: docker-compose build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo service docker start

    - name: Deploy application
      run: docker-compose up -d

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker images to Docker Hub
      run: |
        docker-compose push
        docker push yourdockerhubusername/yourappname:latest
    env:
      DOCKER_BUILDKIT: 1
